### ISSUE TITLE
Player health: 100 health points when you spawn

### ISSUE THREAD

**Issue by LiveG-Technologies** [neontribe/untangled-2017#19]

**Comment by LiveG-Technologies** [comment]
Still in progress - Health bars!

**Comment by LiveG-Technologies** [comment]
How's the health bars, @Spannner?

**Comment by whizzer0** [comment]
It emails me for every one of these… my poor inbox…

**Comment by Spannner** [comment]
@LiveG-Technologies I've just finished all my work on player names forever now, so HUD is next!

@whizzer0 try unwatching the repo
