### ISSUE TITLE
Single folder version

### ISSUE THREAD

**Issue by Spannner** [neontribe/untangled-2017#59]
Is it possible to make a version where all the required modules are in the same folder so that it can be used on all Raspberry Pi computers.

**Comment by LiveG-Technologies** [comment]
That would take forever to make/download from GitHub. There is `./install.sh`! Just use my cURL command (in an empty folder): `curl -sS https://raw.githubusercontent.com/neontribe/untangled-2017/60122605c06e80037281c7be5e01ffa25cf567bd/curl.sh | bash`
